name: Build
on:
  push:
    branches:
      - main

jobs:
  client:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: npx prettier --check .
      - run: yarn build

  server:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run ./check.sh
      - run: ./build.sh
