name: Build
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login ghcr.io -u $ --password-stdin
      - run: docker pull ghcr.io/samestep/whisper-web:latest
      - run: |
          docker build . --pull \
            --cache-from ghcr.io/samestep/whisper-web:latest \
            --tag ghcr.io/samestep/whisper-web:latest
      - run: docker push ghcr.io/samestep/whisper-web:latest

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: npx prettier --check .

  pages:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
